version: '3.8'

services:
  christmas:
    build: .
    container_name: christmas-app
    ports:
      - "8080:8080"
    volumes:
      # Mount thư mục music để data.json được lưu ra ngoài container
      - ./music:/app/music
    restart: unless-stopped

